[window]
padding = { x = 5, y = 5 }
startup_mode = "Maximized"
resize_increments = true
dynamic_title = true
option_as_alt = "Both"

[font]
normal.family = "JetBrains Mono NL"
normal.style = "Regular"
bold.style = "Regular"
italic.style = "Regular"
bold_italic.style = "Regular"
size = 16

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Block"
style.blinking = "Always"
blink_interval = 500
