[window]
padding = { x = 5, y = 5 }
startup_mode = "Maximized"
resize_increments = true
dynamic_title = true
option_as_alt = "Both"

[font]
normal.family = "JetBrains Mono NL"
normal.style = "Regular"
bold.style = "Regular"
italic.style = "Regular"
bold_italic.style = "Regular"
size = 16

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Block"
style.blinking = "Always"
blink_interval = 500

[colors.primary]
background = '#f7f7f7'
foreground = '#434343'

[colors.cursor]
text = '#f7f7f7'
cursor = '#434343'

[colors.normal]
black = '#000000'
red = '#aa3731'
green = '#448c27'
yellow = '#cb9000'
blue = '#325cc0'
magenta = '#7a3e9d'
cyan = '#0083b2'
white = '#bbbbbb'

[colors.bright]
black = '#777777'
red = '#f05050'
green = '#60cb00'
yellow = '#ffbc5d'
blue = '#007acc'
magenta = '#e64ce6'
cyan = '#00aacb'
white = '#ffffff'
